// import type { Metadata } from "next";
// import "./globals.css";

import LayoutDataLayer from "@/components/layout/LayoutDataLayer";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <Container>
    <LayoutDataLayer>{children}</LayoutDataLayer>
    // <RLayout>{children}</RLayout>
    // </Container>
  );
}
