import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const vodafone = localFont({
  src: [
    {
      path: "../public/fonts/vodafone/Vodafone-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/vodafone/Vodafone.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/vodafone/Vodafone-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/vodafone/Vodafone-ExtraBold.woff2",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-vodafone",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="size-full">
      <body
        className={`${vodafone.variable} size-full font-vodafone antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
